- name: Create EC2 instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Launch instance
      amazon.aws.ec2_instance:
        key_name: smartpro
        instance_type: t2.micro
        image:
          id: ami-00b8917ae86a424c9
        wait: yes
        security_groups:
          - default
        count: 1
        vpc_subnet_id: subnet-084a5ca8cfa595166
        network:
          assign_public_ip: yes
      register: ec2

    # - name: Debug EC2 instances
    #   debug:
    #     var: ec2.instances

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -i ~/.ssh/smartpro.pem"
        groupname: dynamic_hosts
      with_items: "{{ ec2.instances }}"

- name: Wait for EC2 instance to be running
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Wait for the instance to be in 'running' state
      wait_for:
        timeout: 320 
        delay: 120
        host: "{{ ec2.instances[0].network_interfaces[0].association.public_ip }}" 
        port: 22
        state: started

- name: Install Python3
  hosts: dynamic_hosts
  become: true
  vars:
    ansible_ssh_private_key_file: "~/.ssh/smartpro.pem"
    ansible_user: ec2-user
  tasks:
    - name: Update package manager and install Python3
      ansible.builtin.shell:
        cmd: sudo yum update -y && sudo yum install -y python3

- name: Create AMI and Terminate EC2
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create AMI
      amazon.aws.ec2_ami:
        instance_id: "{{ ec2.instance_ids[0] }}"
        wait: yes
        name: My AMI
      register: ami

    - name: Terminate instances
      amazon.aws.ec2_instance:
        state: absent
        instance_ids: "{{ ec2.instance_ids[0] }}"